services:
  linkding:
    image: sissbruecker/linkding:latest
    restart: always
    container_name: linkding
    hostname: linkding
    env_file:
      - ../../../docker-server-private/env/linkding/linkding-secrets.env
    volumes:
      - linkding-data:/etc/linkding/data:rw
      - /var/log/docker/linkding:/log:rw
    ports:
      - 192.168.1.12:8084:9090
#    depends_on:
#      - linkding-backup
    networks:
      bridge:
        ipv4_address: 192.168.10.60
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

#  linkding-backup:
#    image: backup:latest
#    restart: always
#    container_name: linkding-backup
#    hostname: linkding-backup
#    env_file:
#      - ../../../docker-server-private/env/linkding/linkding-backup-secrets.env
#    volumes:
#      - ./backup/scripts:/app/lib:rw
#      - linkding-data:/data:rw
#      - backup-rclone-config:/root/.config/rclone:rw
#      - backup-gpg-config:/root/.gnupg:rw
#    networks:
#      bridge:
#        ipv4_address: 192.168.10.11
#    logging:
#      driver: "json-file"
#      options:
#        max-file: "3"
#        max-size: "10m"

networks:
  bridge:
    external: true
    name: docker-bridge

volumes:
  linkding-data:
    external: true
    name: linkding-data

  backup-rclone-config:
    external: true
    name: backup-rclone-config

  backup-gpg-config:
    external: true
    name: backup-gpg-config
