services:
  fireflyiii:
    image: fireflyiii/core:latest
    restart: always
    container_name: fireflyiii
    hostname: fireflyiii
    env_file:
      - ./fireflyiii.env
      - ../../../docker-server-private/env/fireflyiii/fireflyiii-secrets.env
    environment:
      - TRUSTED_PROXIES=**
      - DB_CONNECTION=mysql
      - DB_HOST=fireflyiii-db
      - DB_PORT=3306
    volumes:
      - fireflyiii-upload:/var/www/html/storage/upload:rw
    ports:
      - 192.168.1.12:8081:8080
    networks:
      bridge:
        ipv4_address: 192.168.10.20
    depends_on:
      - fireflyiii-db
      - fireflyiii-backup
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  fireflyiii-db:
    image: mariadb:latest
    restart: always
    container_name: fireflyiii-db
    hostname: fireflyiii-db
    env_file:
      - ../../../docker-server-private/env/fireflyiii/fireflyiii-db-secrets.env
    volumes:
      - fireflyiii-db:/var/lib/mysql:rw
    networks:
      bridge:
        ipv4_address: 192.168.10.21
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  fireflyiii-backup:
    image: backup:latest
    restart: always
    container_name: fireflyiii-backup
    hostname: fireflyiii-backup
    env_file:
      - ../../../docker-server-private/env/fireflyiii/fireflyiii-backup-secrets.env
    volumes:
      - ./backup/scripts:/app/lib:rw
      - fireflyiii-upload:/data/upload:rw
      - fireflyiii-db:/data/db:rw
      - backup-rclone-config:/root/.config/rclone:rw
      - backup-gpg-config:/root/.gnupg:rw
    networks:
      bridge:
        ipv4_address: 192.168.10.22
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

networks:
  bridge:
    external: true
    name: docker-bridge

volumes:
  fireflyiii-upload:
    external: true
    name: fireflyiii-upload

  fireflyiii-db:
    external: true
    name: fireflyiii-db

  backup-rclone-config:
    external: true
    name: backup-rclone-config

  backup-gpg-config:
    external: true
    name: backup-gpg-config
